// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: AirConditioningDevice.proto

package AircondioningDevice.proto.ac;

public interface ACResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:AirConditioningDevice.ACResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.AirConditioningDevice.AirConditioning airConditioning = 1;</code>
   */
  boolean hasAirConditioning();
  /**
   * <code>.AirConditioningDevice.AirConditioning airConditioning = 1;</code>
   */
  AircondioningDevice.proto.ac.AirConditioning getAirConditioning();
  /**
   * <code>.AirConditioningDevice.AirConditioning airConditioning = 1;</code>
   */
  AircondioningDevice.proto.ac.AirConditioningOrBuilder getAirConditioningOrBuilder();
}
