// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: AirConditioningDevice.proto

package AircondioningDevice.proto.ac;

public interface AirConditioningOrBuilder extends
    // @@protoc_insertion_point(interface_extends:AirConditioningDevice.AirConditioning)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 deviceId = 1;</code>
   */
  int getDeviceId();

  /**
   * <code>string name = 2;</code>
   */
  java.lang.String getName();
  /**
   * <code>string name = 2;</code>
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>string location = 3;</code>
   */
  java.lang.String getLocation();
  /**
   * <code>string location = 3;</code>
   */
  com.google.protobuf.ByteString
      getLocationBytes();

  /**
   * <code>string status = 4;</code>
   */
  java.lang.String getStatus();
  /**
   * <code>string status = 4;</code>
   */
  com.google.protobuf.ByteString
      getStatusBytes();

  /**
   * <code>int32 newTempature = 5;</code>
   */
  int getNewTempature();
}
