// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: AirConditioningDevice.proto

package AircondioningDevice.proto.ac;

public final class ClassName {
  private ClassName() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_AirConditioningDevice_AirConditioning_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_AirConditioningDevice_AirConditioning_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_AirConditioningDevice_deviceIDRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_AirConditioningDevice_deviceIDRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_AirConditioningDevice_Response_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_AirConditioningDevice_Response_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_AirConditioningDevice_TempRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_AirConditioningDevice_TempRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_AirConditioningDevice_ACResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_AirConditioningDevice_ACResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\033AirConditioningDevice.proto\022\025AirCondit" +
      "ioningDevice\"i\n\017AirConditioning\022\020\n\010devic" +
      "eId\030\001 \001(\005\022\014\n\004name\030\002 \001(\t\022\020\n\010location\030\003 \001(" +
      "\t\022\016\n\006status\030\004 \001(\t\022\024\n\014newTempature\030\005 \001(\005\"" +
      "$\n\017deviceIDRequest\022\021\n\tdevice_id\030\001 \001(\005\"\034\n" +
      "\010Response\022\020\n\010response\030\001 \001(\t\"2\n\013TempReque" +
      "st\022\021\n\tdevice_id\030\001 \001(\005\022\020\n\010new_temp\030\002 \001(\005\"" +
      "M\n\nACResponse\022?\n\017airConditioning\030\001 \001(\0132&" +
      ".AirConditioningDevice.AirConditioning2\241" +
      "\002\n\027Airconditioning_service\022]\n\016currentDet" +
      "ails\022&.AirConditioningDevice.deviceIDReq" +
      "uest\032!.AirConditioningDevice.ACResponse\"" +
      "\000\022R\n\007setTemp\022\".AirConditioningDevice.Tem" +
      "pRequest\032!.AirConditioningDevice.ACRespo" +
      "nse\"\000\022S\n\006setOff\022&.AirConditioningDevice." +
      "deviceIDRequest\032\037.AirConditioningDevice." +
      "Response\"\000B+\n\034AircondioningDevice.proto." +
      "acB\tClassNameP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_AirConditioningDevice_AirConditioning_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_AirConditioningDevice_AirConditioning_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_AirConditioningDevice_AirConditioning_descriptor,
        new java.lang.String[] { "DeviceId", "Name", "Location", "Status", "NewTempature", });
    internal_static_AirConditioningDevice_deviceIDRequest_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_AirConditioningDevice_deviceIDRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_AirConditioningDevice_deviceIDRequest_descriptor,
        new java.lang.String[] { "DeviceId", });
    internal_static_AirConditioningDevice_Response_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_AirConditioningDevice_Response_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_AirConditioningDevice_Response_descriptor,
        new java.lang.String[] { "Response", });
    internal_static_AirConditioningDevice_TempRequest_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_AirConditioningDevice_TempRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_AirConditioningDevice_TempRequest_descriptor,
        new java.lang.String[] { "DeviceId", "NewTemp", });
    internal_static_AirConditioningDevice_ACResponse_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_AirConditioningDevice_ACResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_AirConditioningDevice_ACResponse_descriptor,
        new java.lang.String[] { "AirConditioning", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
