// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: AirConditioningDevice.proto

package AircondioningDevice.proto.ac;

public interface deviceIDRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:AirConditioningDevice.deviceIDRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 device_id = 1;</code>
   */
  int getDeviceId();
}
