// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: AirConditioningDevice.proto

package AircondioningDevice.proto.ac;

public interface TempRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:AirConditioningDevice.TempRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 device_id = 1;</code>
   */
  int getDeviceId();

  /**
   * <code>int32 new_temp = 2;</code>
   */
  int getNewTemp();
}
