// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Tv.proto

package TVDevice.proto.tv;

public final class ClassName {
  private ClassName() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Tv_TV_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Tv_TV_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Tv_TVStatusRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Tv_TVStatusRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Tv_exact_update_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Tv_exact_update_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Tv_update_request_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Tv_update_request_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Tv_TVStatusResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Tv_TVStatusResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Tv_TVDetailResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Tv_TVDetailResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\010Tv.proto\022\002Tv\"K\n\002TV\022\r\n\005tv_id\030\001 \001(\005\022\027\n\017d" +
      "evice_location\030\002 \001(\t\022\016\n\006status\030\003 \001(\t\022\r\n\005" +
      "exact\030\004 \001(\005\" \n\017TVStatusRequest\022\r\n\005tv_id\030" +
      "\001 \001(\005\"4\n\014exact_update\022\r\n\005tv_id\030\001 \001(\005\022\025\n\r" +
      "exact_request\030\002 \001(\005\"\037\n\016update_request\022\r\n" +
      "\005tv_id\030\001 \001(\005\"&\n\020TVStatusResponse\022\022\n\002tv\030\001" +
      " \001(\0132\006.Tv.TV\"&\n\020TVDetailResponse\022\022\n\002tv\030\001" +
      " \001(\0132\006.Tv.TV2\353\001\n\tTVService\0229\n\nshowStatus" +
      "\022\023.Tv.TVStatusRequest\032\024.Tv.TVStatusRespo" +
      "nse\"\000\022:\n\016setExactVolume\022\020.Tv.exact_updat" +
      "e\032\024.Tv.TVDetailResponse\"\000\0222\n\004tVOn\022\022.Tv.u" +
      "pdate_request\032\024.Tv.TVDetailResponse\"\000\0223\n" +
      "\005tVOff\022\022.Tv.update_request\032\024.Tv.TVDetail" +
      "Response\"\000B \n\021TVDevice.proto.tvB\tClassNa" +
      "meP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_Tv_TV_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Tv_TV_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Tv_TV_descriptor,
        new java.lang.String[] { "TvId", "DeviceLocation", "Status", "Exact", });
    internal_static_Tv_TVStatusRequest_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_Tv_TVStatusRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Tv_TVStatusRequest_descriptor,
        new java.lang.String[] { "TvId", });
    internal_static_Tv_exact_update_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_Tv_exact_update_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Tv_exact_update_descriptor,
        new java.lang.String[] { "TvId", "ExactRequest", });
    internal_static_Tv_update_request_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_Tv_update_request_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Tv_update_request_descriptor,
        new java.lang.String[] { "TvId", });
    internal_static_Tv_TVStatusResponse_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_Tv_TVStatusResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Tv_TVStatusResponse_descriptor,
        new java.lang.String[] { "Tv", });
    internal_static_Tv_TVDetailResponse_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_Tv_TVDetailResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Tv_TVDetailResponse_descriptor,
        new java.lang.String[] { "Tv", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
