// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: TVDevice.proto

package TVDevice.proto.tv;

public final class ClassName {
  private ClassName() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_TVDevice_TV_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_TVDevice_TV_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_TVDevice_TVStatusRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_TVDevice_TVStatusRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_TVDevice_exact_update_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_TVDevice_exact_update_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_TVDevice_update_request_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_TVDevice_update_request_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_TVDevice_TVStatusResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_TVDevice_TVStatusResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_TVDevice_TVDetailResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_TVDevice_TVDetailResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016TVDevice.proto\022\010TVDevice\"<\n\002TV\022\r\n\005tv_i" +
      "d\030\001 \001(\005\022\027\n\017device_location\030\003 \001(\t\022\016\n\006stat" +
      "us\030\004 \001(\t\" \n\017TVStatusRequest\022\r\n\005tv_id\030\001 \001" +
      "(\005\"4\n\014exact_update\022\r\n\005tv_id\030\001 \001(\005\022\025\n\rexa" +
      "ct_request\030\002 \001(\005\"/\n\016update_request\022\r\n\005tv" +
      "_id\030\001 \001(\005\022\016\n\006update\030\002 \001(\t\",\n\020TVStatusRes" +
      "ponse\022\030\n\002tv\030\001 \001(\0132\014.TVDevice.TV\",\n\020TVDet" +
      "ailResponse\022\030\n\002tv\030\001 \001(\0132\014.TVDevice.TV2\237\002" +
      "\n\rHeaterService\022E\n\nShowStatus\022\031.TVDevice" +
      ".TVStatusRequest\032\032.TVDevice.TVStatusResp" +
      "onse\"\000\022F\n\016SetExactVolume\022\026.TVDevice.exac" +
      "t_update\032\032.TVDevice.TVDetailResponse\"\000\022>" +
      "\n\004TVOn\022\030.TVDevice.update_request\032\032.TVDev" +
      "ice.TVDetailResponse\"\000\022?\n\005TVOff\022\030.TVDevi" +
      "ce.update_request\032\032.TVDevice.TVDetailRes" +
      "ponse\"\000B \n\021TVDevice.proto.tvB\tClassNameP" +
      "\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_TVDevice_TV_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_TVDevice_TV_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_TVDevice_TV_descriptor,
        new java.lang.String[] { "TvId", "DeviceLocation", "Status", });
    internal_static_TVDevice_TVStatusRequest_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_TVDevice_TVStatusRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_TVDevice_TVStatusRequest_descriptor,
        new java.lang.String[] { "TvId", });
    internal_static_TVDevice_exact_update_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_TVDevice_exact_update_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_TVDevice_exact_update_descriptor,
        new java.lang.String[] { "TvId", "ExactRequest", });
    internal_static_TVDevice_update_request_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_TVDevice_update_request_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_TVDevice_update_request_descriptor,
        new java.lang.String[] { "TvId", "Update", });
    internal_static_TVDevice_TVStatusResponse_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_TVDevice_TVStatusResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_TVDevice_TVStatusResponse_descriptor,
        new java.lang.String[] { "Tv", });
    internal_static_TVDevice_TVDetailResponse_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_TVDevice_TVDetailResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_TVDevice_TVDetailResponse_descriptor,
        new java.lang.String[] { "Tv", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
