// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: TVDevice.proto

package TVDevice.proto.tv;

public interface exact_updateOrBuilder extends
    // @@protoc_insertion_point(interface_extends:TVDevice.exact_update)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 tv_id = 1;</code>
   */
  int getTvId();

  /**
   * <code>int32 exact_request = 2;</code>
   */
  int getExactRequest();
}
