// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Tv.proto

package TVDevice.proto.tv;

/**
 * Protobuf type {@code Tv.TVDetailResponse}
 */
public  final class TVDetailResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:Tv.TVDetailResponse)
    TVDetailResponseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use TVDetailResponse.newBuilder() to construct.
  private TVDetailResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private TVDetailResponse() {
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private TVDetailResponse(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            TVDevice.proto.tv.TV.Builder subBuilder = null;
            if (tv_ != null) {
              subBuilder = tv_.toBuilder();
            }
            tv_ = input.readMessage(TVDevice.proto.tv.TV.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(tv_);
              tv_ = subBuilder.buildPartial();
            }

            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return TVDevice.proto.tv.ClassName.internal_static_Tv_TVDetailResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return TVDevice.proto.tv.ClassName.internal_static_Tv_TVDetailResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            TVDevice.proto.tv.TVDetailResponse.class, TVDevice.proto.tv.TVDetailResponse.Builder.class);
  }

  public static final int TV_FIELD_NUMBER = 1;
  private TVDevice.proto.tv.TV tv_;
  /**
   * <code>.Tv.TV tv = 1;</code>
   */
  public boolean hasTv() {
    return tv_ != null;
  }
  /**
   * <code>.Tv.TV tv = 1;</code>
   */
  public TVDevice.proto.tv.TV getTv() {
    return tv_ == null ? TVDevice.proto.tv.TV.getDefaultInstance() : tv_;
  }
  /**
   * <code>.Tv.TV tv = 1;</code>
   */
  public TVDevice.proto.tv.TVOrBuilder getTvOrBuilder() {
    return getTv();
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (tv_ != null) {
      output.writeMessage(1, getTv());
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (tv_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getTv());
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof TVDevice.proto.tv.TVDetailResponse)) {
      return super.equals(obj);
    }
    TVDevice.proto.tv.TVDetailResponse other = (TVDevice.proto.tv.TVDetailResponse) obj;

    boolean result = true;
    result = result && (hasTv() == other.hasTv());
    if (hasTv()) {
      result = result && getTv()
          .equals(other.getTv());
    }
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasTv()) {
      hash = (37 * hash) + TV_FIELD_NUMBER;
      hash = (53 * hash) + getTv().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static TVDevice.proto.tv.TVDetailResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static TVDevice.proto.tv.TVDetailResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static TVDevice.proto.tv.TVDetailResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static TVDevice.proto.tv.TVDetailResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static TVDevice.proto.tv.TVDetailResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static TVDevice.proto.tv.TVDetailResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static TVDevice.proto.tv.TVDetailResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static TVDevice.proto.tv.TVDetailResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static TVDevice.proto.tv.TVDetailResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static TVDevice.proto.tv.TVDetailResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static TVDevice.proto.tv.TVDetailResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static TVDevice.proto.tv.TVDetailResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(TVDevice.proto.tv.TVDetailResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code Tv.TVDetailResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:Tv.TVDetailResponse)
      TVDevice.proto.tv.TVDetailResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return TVDevice.proto.tv.ClassName.internal_static_Tv_TVDetailResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return TVDevice.proto.tv.ClassName.internal_static_Tv_TVDetailResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              TVDevice.proto.tv.TVDetailResponse.class, TVDevice.proto.tv.TVDetailResponse.Builder.class);
    }

    // Construct using TVDevice.proto.tv.TVDetailResponse.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      if (tvBuilder_ == null) {
        tv_ = null;
      } else {
        tv_ = null;
        tvBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return TVDevice.proto.tv.ClassName.internal_static_Tv_TVDetailResponse_descriptor;
    }

    @java.lang.Override
    public TVDevice.proto.tv.TVDetailResponse getDefaultInstanceForType() {
      return TVDevice.proto.tv.TVDetailResponse.getDefaultInstance();
    }

    @java.lang.Override
    public TVDevice.proto.tv.TVDetailResponse build() {
      TVDevice.proto.tv.TVDetailResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public TVDevice.proto.tv.TVDetailResponse buildPartial() {
      TVDevice.proto.tv.TVDetailResponse result = new TVDevice.proto.tv.TVDetailResponse(this);
      if (tvBuilder_ == null) {
        result.tv_ = tv_;
      } else {
        result.tv_ = tvBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof TVDevice.proto.tv.TVDetailResponse) {
        return mergeFrom((TVDevice.proto.tv.TVDetailResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(TVDevice.proto.tv.TVDetailResponse other) {
      if (other == TVDevice.proto.tv.TVDetailResponse.getDefaultInstance()) return this;
      if (other.hasTv()) {
        mergeTv(other.getTv());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      TVDevice.proto.tv.TVDetailResponse parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (TVDevice.proto.tv.TVDetailResponse) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private TVDevice.proto.tv.TV tv_ = null;
    private com.google.protobuf.SingleFieldBuilderV3<
        TVDevice.proto.tv.TV, TVDevice.proto.tv.TV.Builder, TVDevice.proto.tv.TVOrBuilder> tvBuilder_;
    /**
     * <code>.Tv.TV tv = 1;</code>
     */
    public boolean hasTv() {
      return tvBuilder_ != null || tv_ != null;
    }
    /**
     * <code>.Tv.TV tv = 1;</code>
     */
    public TVDevice.proto.tv.TV getTv() {
      if (tvBuilder_ == null) {
        return tv_ == null ? TVDevice.proto.tv.TV.getDefaultInstance() : tv_;
      } else {
        return tvBuilder_.getMessage();
      }
    }
    /**
     * <code>.Tv.TV tv = 1;</code>
     */
    public Builder setTv(TVDevice.proto.tv.TV value) {
      if (tvBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        tv_ = value;
        onChanged();
      } else {
        tvBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.Tv.TV tv = 1;</code>
     */
    public Builder setTv(
        TVDevice.proto.tv.TV.Builder builderForValue) {
      if (tvBuilder_ == null) {
        tv_ = builderForValue.build();
        onChanged();
      } else {
        tvBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.Tv.TV tv = 1;</code>
     */
    public Builder mergeTv(TVDevice.proto.tv.TV value) {
      if (tvBuilder_ == null) {
        if (tv_ != null) {
          tv_ =
            TVDevice.proto.tv.TV.newBuilder(tv_).mergeFrom(value).buildPartial();
        } else {
          tv_ = value;
        }
        onChanged();
      } else {
        tvBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.Tv.TV tv = 1;</code>
     */
    public Builder clearTv() {
      if (tvBuilder_ == null) {
        tv_ = null;
        onChanged();
      } else {
        tv_ = null;
        tvBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.Tv.TV tv = 1;</code>
     */
    public TVDevice.proto.tv.TV.Builder getTvBuilder() {
      
      onChanged();
      return getTvFieldBuilder().getBuilder();
    }
    /**
     * <code>.Tv.TV tv = 1;</code>
     */
    public TVDevice.proto.tv.TVOrBuilder getTvOrBuilder() {
      if (tvBuilder_ != null) {
        return tvBuilder_.getMessageOrBuilder();
      } else {
        return tv_ == null ?
            TVDevice.proto.tv.TV.getDefaultInstance() : tv_;
      }
    }
    /**
     * <code>.Tv.TV tv = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        TVDevice.proto.tv.TV, TVDevice.proto.tv.TV.Builder, TVDevice.proto.tv.TVOrBuilder> 
        getTvFieldBuilder() {
      if (tvBuilder_ == null) {
        tvBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            TVDevice.proto.tv.TV, TVDevice.proto.tv.TV.Builder, TVDevice.proto.tv.TVOrBuilder>(
                getTv(),
                getParentForChildren(),
                isClean());
        tv_ = null;
      }
      return tvBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:Tv.TVDetailResponse)
  }

  // @@protoc_insertion_point(class_scope:Tv.TVDetailResponse)
  private static final TVDevice.proto.tv.TVDetailResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new TVDevice.proto.tv.TVDetailResponse();
  }

  public static TVDevice.proto.tv.TVDetailResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<TVDetailResponse>
      PARSER = new com.google.protobuf.AbstractParser<TVDetailResponse>() {
    @java.lang.Override
    public TVDetailResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new TVDetailResponse(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<TVDetailResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<TVDetailResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public TVDevice.proto.tv.TVDetailResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

