// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: TVDevice.proto

package TVDevice.proto.tv;

public interface TVOrBuilder extends
    // @@protoc_insertion_point(interface_extends:TVDevice.TV)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 tv_id = 1;</code>
   */
  int getTvId();

  /**
   * <code>string device_location = 3;</code>
   */
  java.lang.String getDeviceLocation();
  /**
   * <code>string device_location = 3;</code>
   */
  com.google.protobuf.ByteString
      getDeviceLocationBytes();

  /**
   * <code>string status = 4;</code>
   */
  java.lang.String getStatus();
  /**
   * <code>string status = 4;</code>
   */
  com.google.protobuf.ByteString
      getStatusBytes();
}
