// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Tv.proto

package TVDevice.proto.tv;

public interface TVOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Tv.TV)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 tv_id = 1;</code>
   */
  int getTvId();

  /**
   * <code>string device_location = 2;</code>
   */
  java.lang.String getDeviceLocation();
  /**
   * <code>string device_location = 2;</code>
   */
  com.google.protobuf.ByteString
      getDeviceLocationBytes();

  /**
   * <code>string status = 3;</code>
   */
  java.lang.String getStatus();
  /**
   * <code>string status = 3;</code>
   */
  com.google.protobuf.ByteString
      getStatusBytes();

  /**
   * <code>int32 exact = 4;</code>
   */
  int getExact();
}
