// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: TVDevice.proto

package TVDevice.proto.tv;

public interface TVStatusResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:TVDevice.TVStatusResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.TVDevice.TV tv = 1;</code>
   */
  boolean hasTv();
  /**
   * <code>.TVDevice.TV tv = 1;</code>
   */
  TVDevice.proto.tv.TV getTv();
  /**
   * <code>.TVDevice.TV tv = 1;</code>
   */
  TVDevice.proto.tv.TVOrBuilder getTvOrBuilder();
}
