// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: TVDevice.proto

package TVDevice.proto.tv;

public interface TVStatusRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:TVDevice.TVStatusRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 tv_id = 1;</code>
   */
  int getTvId();
}
