// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Tv.proto

package TVDevice.proto.tv;

public interface update_requestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Tv.update_request)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 tv_id = 1;</code>
   */
  int getTvId();
}
