// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: TVDevice.proto

package TVDevice.proto.tv;

public interface update_requestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:TVDevice.update_request)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 tv_id = 1;</code>
   */
  int getTvId();

  /**
   * <code>string update = 2;</code>
   */
  java.lang.String getUpdate();
  /**
   * <code>string update = 2;</code>
   */
  com.google.protobuf.ByteString
      getUpdateBytes();
}
