// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: LightsDevice.proto

package LightsDevice.proto.li;

public interface lightToUpdateRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:LightsDevice.lightToUpdateRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 light_id = 1;</code>
   */
  int getLightId();

  /**
   * <code>string request = 2;</code>
   */
  java.lang.String getRequest();
  /**
   * <code>string request = 2;</code>
   */
  com.google.protobuf.ByteString
      getRequestBytes();
}
