// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: LightsDevice.proto

package LightsDevice.proto.li;

public interface light_status_requestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:LightsDevice.light_status_request)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 light_id = 1;</code>
   */
  int getLightId();
}
