// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: LightsDevice.proto

package LightsDevice.proto.li;

/**
 * Protobuf type {@code LightsDevice.Lights}
 */
public  final class Lights extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:LightsDevice.Lights)
    LightsOrBuilder {
private static final long serialVersionUID = 0L;
  // Use Lights.newBuilder() to construct.
  private Lights(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private Lights() {
    lightId_ = 0;
    lightLocation_ = "";
    lightStatus_ = "";
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private Lights(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {

            lightId_ = input.readInt32();
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            lightLocation_ = s;
            break;
          }
          case 26: {
            java.lang.String s = input.readStringRequireUtf8();

            lightStatus_ = s;
            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return LightsDevice.proto.li.ClassName.internal_static_LightsDevice_Lights_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return LightsDevice.proto.li.ClassName.internal_static_LightsDevice_Lights_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            LightsDevice.proto.li.Lights.class, LightsDevice.proto.li.Lights.Builder.class);
  }

  public static final int LIGHT_ID_FIELD_NUMBER = 1;
  private int lightId_;
  /**
   * <code>int32 light_id = 1;</code>
   */
  public int getLightId() {
    return lightId_;
  }

  public static final int LIGHT_LOCATION_FIELD_NUMBER = 2;
  private volatile java.lang.Object lightLocation_;
  /**
   * <code>string light_location = 2;</code>
   */
  public java.lang.String getLightLocation() {
    java.lang.Object ref = lightLocation_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      lightLocation_ = s;
      return s;
    }
  }
  /**
   * <code>string light_location = 2;</code>
   */
  public com.google.protobuf.ByteString
      getLightLocationBytes() {
    java.lang.Object ref = lightLocation_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      lightLocation_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int LIGHT_STATUS_FIELD_NUMBER = 3;
  private volatile java.lang.Object lightStatus_;
  /**
   * <code>string light_status = 3;</code>
   */
  public java.lang.String getLightStatus() {
    java.lang.Object ref = lightStatus_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      lightStatus_ = s;
      return s;
    }
  }
  /**
   * <code>string light_status = 3;</code>
   */
  public com.google.protobuf.ByteString
      getLightStatusBytes() {
    java.lang.Object ref = lightStatus_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      lightStatus_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (lightId_ != 0) {
      output.writeInt32(1, lightId_);
    }
    if (!getLightLocationBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, lightLocation_);
    }
    if (!getLightStatusBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, lightStatus_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (lightId_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(1, lightId_);
    }
    if (!getLightLocationBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, lightLocation_);
    }
    if (!getLightStatusBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, lightStatus_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof LightsDevice.proto.li.Lights)) {
      return super.equals(obj);
    }
    LightsDevice.proto.li.Lights other = (LightsDevice.proto.li.Lights) obj;

    boolean result = true;
    result = result && (getLightId()
        == other.getLightId());
    result = result && getLightLocation()
        .equals(other.getLightLocation());
    result = result && getLightStatus()
        .equals(other.getLightStatus());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + LIGHT_ID_FIELD_NUMBER;
    hash = (53 * hash) + getLightId();
    hash = (37 * hash) + LIGHT_LOCATION_FIELD_NUMBER;
    hash = (53 * hash) + getLightLocation().hashCode();
    hash = (37 * hash) + LIGHT_STATUS_FIELD_NUMBER;
    hash = (53 * hash) + getLightStatus().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static LightsDevice.proto.li.Lights parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static LightsDevice.proto.li.Lights parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static LightsDevice.proto.li.Lights parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static LightsDevice.proto.li.Lights parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static LightsDevice.proto.li.Lights parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static LightsDevice.proto.li.Lights parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static LightsDevice.proto.li.Lights parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static LightsDevice.proto.li.Lights parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static LightsDevice.proto.li.Lights parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static LightsDevice.proto.li.Lights parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static LightsDevice.proto.li.Lights parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static LightsDevice.proto.li.Lights parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(LightsDevice.proto.li.Lights prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code LightsDevice.Lights}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:LightsDevice.Lights)
      LightsDevice.proto.li.LightsOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return LightsDevice.proto.li.ClassName.internal_static_LightsDevice_Lights_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return LightsDevice.proto.li.ClassName.internal_static_LightsDevice_Lights_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              LightsDevice.proto.li.Lights.class, LightsDevice.proto.li.Lights.Builder.class);
    }

    // Construct using LightsDevice.proto.li.Lights.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      lightId_ = 0;

      lightLocation_ = "";

      lightStatus_ = "";

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return LightsDevice.proto.li.ClassName.internal_static_LightsDevice_Lights_descriptor;
    }

    @java.lang.Override
    public LightsDevice.proto.li.Lights getDefaultInstanceForType() {
      return LightsDevice.proto.li.Lights.getDefaultInstance();
    }

    @java.lang.Override
    public LightsDevice.proto.li.Lights build() {
      LightsDevice.proto.li.Lights result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public LightsDevice.proto.li.Lights buildPartial() {
      LightsDevice.proto.li.Lights result = new LightsDevice.proto.li.Lights(this);
      result.lightId_ = lightId_;
      result.lightLocation_ = lightLocation_;
      result.lightStatus_ = lightStatus_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof LightsDevice.proto.li.Lights) {
        return mergeFrom((LightsDevice.proto.li.Lights)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(LightsDevice.proto.li.Lights other) {
      if (other == LightsDevice.proto.li.Lights.getDefaultInstance()) return this;
      if (other.getLightId() != 0) {
        setLightId(other.getLightId());
      }
      if (!other.getLightLocation().isEmpty()) {
        lightLocation_ = other.lightLocation_;
        onChanged();
      }
      if (!other.getLightStatus().isEmpty()) {
        lightStatus_ = other.lightStatus_;
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      LightsDevice.proto.li.Lights parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (LightsDevice.proto.li.Lights) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private int lightId_ ;
    /**
     * <code>int32 light_id = 1;</code>
     */
    public int getLightId() {
      return lightId_;
    }
    /**
     * <code>int32 light_id = 1;</code>
     */
    public Builder setLightId(int value) {
      
      lightId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 light_id = 1;</code>
     */
    public Builder clearLightId() {
      
      lightId_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object lightLocation_ = "";
    /**
     * <code>string light_location = 2;</code>
     */
    public java.lang.String getLightLocation() {
      java.lang.Object ref = lightLocation_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        lightLocation_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string light_location = 2;</code>
     */
    public com.google.protobuf.ByteString
        getLightLocationBytes() {
      java.lang.Object ref = lightLocation_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        lightLocation_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string light_location = 2;</code>
     */
    public Builder setLightLocation(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      lightLocation_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string light_location = 2;</code>
     */
    public Builder clearLightLocation() {
      
      lightLocation_ = getDefaultInstance().getLightLocation();
      onChanged();
      return this;
    }
    /**
     * <code>string light_location = 2;</code>
     */
    public Builder setLightLocationBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      lightLocation_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object lightStatus_ = "";
    /**
     * <code>string light_status = 3;</code>
     */
    public java.lang.String getLightStatus() {
      java.lang.Object ref = lightStatus_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        lightStatus_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string light_status = 3;</code>
     */
    public com.google.protobuf.ByteString
        getLightStatusBytes() {
      java.lang.Object ref = lightStatus_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        lightStatus_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string light_status = 3;</code>
     */
    public Builder setLightStatus(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      lightStatus_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string light_status = 3;</code>
     */
    public Builder clearLightStatus() {
      
      lightStatus_ = getDefaultInstance().getLightStatus();
      onChanged();
      return this;
    }
    /**
     * <code>string light_status = 3;</code>
     */
    public Builder setLightStatusBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      lightStatus_ = value;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:LightsDevice.Lights)
  }

  // @@protoc_insertion_point(class_scope:LightsDevice.Lights)
  private static final LightsDevice.proto.li.Lights DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new LightsDevice.proto.li.Lights();
  }

  public static LightsDevice.proto.li.Lights getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Lights>
      PARSER = new com.google.protobuf.AbstractParser<Lights>() {
    @java.lang.Override
    public Lights parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new Lights(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<Lights> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Lights> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public LightsDevice.proto.li.Lights getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

