// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: LightsDevice.proto

package LightsDevice.proto.li;

/**
 * Protobuf type {@code LightsDevice.lightStatusResponse}
 */
public  final class lightStatusResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:LightsDevice.lightStatusResponse)
    lightStatusResponseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use lightStatusResponse.newBuilder() to construct.
  private lightStatusResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private lightStatusResponse() {
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private lightStatusResponse(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            LightsDevice.proto.li.Lights.Builder subBuilder = null;
            if (lights_ != null) {
              subBuilder = lights_.toBuilder();
            }
            lights_ = input.readMessage(LightsDevice.proto.li.Lights.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(lights_);
              lights_ = subBuilder.buildPartial();
            }

            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return LightsDevice.proto.li.ClassName.internal_static_LightsDevice_lightStatusResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return LightsDevice.proto.li.ClassName.internal_static_LightsDevice_lightStatusResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            LightsDevice.proto.li.lightStatusResponse.class, LightsDevice.proto.li.lightStatusResponse.Builder.class);
  }

  public static final int LIGHTS_FIELD_NUMBER = 1;
  private LightsDevice.proto.li.Lights lights_;
  /**
   * <code>.LightsDevice.Lights lights = 1;</code>
   */
  public boolean hasLights() {
    return lights_ != null;
  }
  /**
   * <code>.LightsDevice.Lights lights = 1;</code>
   */
  public LightsDevice.proto.li.Lights getLights() {
    return lights_ == null ? LightsDevice.proto.li.Lights.getDefaultInstance() : lights_;
  }
  /**
   * <code>.LightsDevice.Lights lights = 1;</code>
   */
  public LightsDevice.proto.li.LightsOrBuilder getLightsOrBuilder() {
    return getLights();
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (lights_ != null) {
      output.writeMessage(1, getLights());
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (lights_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getLights());
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof LightsDevice.proto.li.lightStatusResponse)) {
      return super.equals(obj);
    }
    LightsDevice.proto.li.lightStatusResponse other = (LightsDevice.proto.li.lightStatusResponse) obj;

    boolean result = true;
    result = result && (hasLights() == other.hasLights());
    if (hasLights()) {
      result = result && getLights()
          .equals(other.getLights());
    }
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasLights()) {
      hash = (37 * hash) + LIGHTS_FIELD_NUMBER;
      hash = (53 * hash) + getLights().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static LightsDevice.proto.li.lightStatusResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static LightsDevice.proto.li.lightStatusResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static LightsDevice.proto.li.lightStatusResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static LightsDevice.proto.li.lightStatusResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static LightsDevice.proto.li.lightStatusResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static LightsDevice.proto.li.lightStatusResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static LightsDevice.proto.li.lightStatusResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static LightsDevice.proto.li.lightStatusResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static LightsDevice.proto.li.lightStatusResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static LightsDevice.proto.li.lightStatusResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static LightsDevice.proto.li.lightStatusResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static LightsDevice.proto.li.lightStatusResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(LightsDevice.proto.li.lightStatusResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code LightsDevice.lightStatusResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:LightsDevice.lightStatusResponse)
      LightsDevice.proto.li.lightStatusResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return LightsDevice.proto.li.ClassName.internal_static_LightsDevice_lightStatusResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return LightsDevice.proto.li.ClassName.internal_static_LightsDevice_lightStatusResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              LightsDevice.proto.li.lightStatusResponse.class, LightsDevice.proto.li.lightStatusResponse.Builder.class);
    }

    // Construct using LightsDevice.proto.li.lightStatusResponse.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      if (lightsBuilder_ == null) {
        lights_ = null;
      } else {
        lights_ = null;
        lightsBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return LightsDevice.proto.li.ClassName.internal_static_LightsDevice_lightStatusResponse_descriptor;
    }

    @java.lang.Override
    public LightsDevice.proto.li.lightStatusResponse getDefaultInstanceForType() {
      return LightsDevice.proto.li.lightStatusResponse.getDefaultInstance();
    }

    @java.lang.Override
    public LightsDevice.proto.li.lightStatusResponse build() {
      LightsDevice.proto.li.lightStatusResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public LightsDevice.proto.li.lightStatusResponse buildPartial() {
      LightsDevice.proto.li.lightStatusResponse result = new LightsDevice.proto.li.lightStatusResponse(this);
      if (lightsBuilder_ == null) {
        result.lights_ = lights_;
      } else {
        result.lights_ = lightsBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof LightsDevice.proto.li.lightStatusResponse) {
        return mergeFrom((LightsDevice.proto.li.lightStatusResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(LightsDevice.proto.li.lightStatusResponse other) {
      if (other == LightsDevice.proto.li.lightStatusResponse.getDefaultInstance()) return this;
      if (other.hasLights()) {
        mergeLights(other.getLights());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      LightsDevice.proto.li.lightStatusResponse parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (LightsDevice.proto.li.lightStatusResponse) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private LightsDevice.proto.li.Lights lights_ = null;
    private com.google.protobuf.SingleFieldBuilderV3<
        LightsDevice.proto.li.Lights, LightsDevice.proto.li.Lights.Builder, LightsDevice.proto.li.LightsOrBuilder> lightsBuilder_;
    /**
     * <code>.LightsDevice.Lights lights = 1;</code>
     */
    public boolean hasLights() {
      return lightsBuilder_ != null || lights_ != null;
    }
    /**
     * <code>.LightsDevice.Lights lights = 1;</code>
     */
    public LightsDevice.proto.li.Lights getLights() {
      if (lightsBuilder_ == null) {
        return lights_ == null ? LightsDevice.proto.li.Lights.getDefaultInstance() : lights_;
      } else {
        return lightsBuilder_.getMessage();
      }
    }
    /**
     * <code>.LightsDevice.Lights lights = 1;</code>
     */
    public Builder setLights(LightsDevice.proto.li.Lights value) {
      if (lightsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        lights_ = value;
        onChanged();
      } else {
        lightsBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.LightsDevice.Lights lights = 1;</code>
     */
    public Builder setLights(
        LightsDevice.proto.li.Lights.Builder builderForValue) {
      if (lightsBuilder_ == null) {
        lights_ = builderForValue.build();
        onChanged();
      } else {
        lightsBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.LightsDevice.Lights lights = 1;</code>
     */
    public Builder mergeLights(LightsDevice.proto.li.Lights value) {
      if (lightsBuilder_ == null) {
        if (lights_ != null) {
          lights_ =
            LightsDevice.proto.li.Lights.newBuilder(lights_).mergeFrom(value).buildPartial();
        } else {
          lights_ = value;
        }
        onChanged();
      } else {
        lightsBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.LightsDevice.Lights lights = 1;</code>
     */
    public Builder clearLights() {
      if (lightsBuilder_ == null) {
        lights_ = null;
        onChanged();
      } else {
        lights_ = null;
        lightsBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.LightsDevice.Lights lights = 1;</code>
     */
    public LightsDevice.proto.li.Lights.Builder getLightsBuilder() {
      
      onChanged();
      return getLightsFieldBuilder().getBuilder();
    }
    /**
     * <code>.LightsDevice.Lights lights = 1;</code>
     */
    public LightsDevice.proto.li.LightsOrBuilder getLightsOrBuilder() {
      if (lightsBuilder_ != null) {
        return lightsBuilder_.getMessageOrBuilder();
      } else {
        return lights_ == null ?
            LightsDevice.proto.li.Lights.getDefaultInstance() : lights_;
      }
    }
    /**
     * <code>.LightsDevice.Lights lights = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        LightsDevice.proto.li.Lights, LightsDevice.proto.li.Lights.Builder, LightsDevice.proto.li.LightsOrBuilder> 
        getLightsFieldBuilder() {
      if (lightsBuilder_ == null) {
        lightsBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            LightsDevice.proto.li.Lights, LightsDevice.proto.li.Lights.Builder, LightsDevice.proto.li.LightsOrBuilder>(
                getLights(),
                getParentForChildren(),
                isClean());
        lights_ = null;
      }
      return lightsBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:LightsDevice.lightStatusResponse)
  }

  // @@protoc_insertion_point(class_scope:LightsDevice.lightStatusResponse)
  private static final LightsDevice.proto.li.lightStatusResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new LightsDevice.proto.li.lightStatusResponse();
  }

  public static LightsDevice.proto.li.lightStatusResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<lightStatusResponse>
      PARSER = new com.google.protobuf.AbstractParser<lightStatusResponse>() {
    @java.lang.Override
    public lightStatusResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new lightStatusResponse(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<lightStatusResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<lightStatusResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public LightsDevice.proto.li.lightStatusResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

