// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: LightsDevice.proto

package LightsDevice.proto.li;

public interface LightsOrBuilder extends
    // @@protoc_insertion_point(interface_extends:LightsDevice.Lights)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 light_id = 1;</code>
   */
  int getLightId();

  /**
   * <code>string light_location = 2;</code>
   */
  java.lang.String getLightLocation();
  /**
   * <code>string light_location = 2;</code>
   */
  com.google.protobuf.ByteString
      getLightLocationBytes();

  /**
   * <code>string light_status = 3;</code>
   */
  java.lang.String getLightStatus();
  /**
   * <code>string light_status = 3;</code>
   */
  com.google.protobuf.ByteString
      getLightStatusBytes();
}
