// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: LightsDevice.proto

package LightsDevice.proto.li;

public interface lightDetailResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:LightsDevice.lightDetailResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.LightsDevice.Lights lights = 1;</code>
   */
  boolean hasLights();
  /**
   * <code>.LightsDevice.Lights lights = 1;</code>
   */
  LightsDevice.proto.li.Lights getLights();
  /**
   * <code>.LightsDevice.Lights lights = 1;</code>
   */
  LightsDevice.proto.li.LightsOrBuilder getLightsOrBuilder();
}
