// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: HeatingDevice.proto

package HeatingDevice.proto.h;

public final class ClassName {
  private ClassName() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_HeatingDevice_Heater_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_HeatingDevice_Heater_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_HeatingDevice_HeaterStatusRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_HeatingDevice_HeaterStatusRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_HeatingDevice_exact_temp_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_HeatingDevice_exact_temp_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_HeatingDevice_HeaterUpdateRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_HeatingDevice_HeaterUpdateRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_HeatingDevice_HeaterStatusResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_HeatingDevice_HeaterStatusResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_HeatingDevice_HeaterDetailResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_HeatingDevice_HeaterDetailResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\023HeatingDevice.proto\022\rHeatingDevice\"g\n\006" +
      "Heater\022\021\n\theater_id\030\001 \001(\005\022\016\n\006device\030\002 \001(" +
      "\t\022\027\n\017device_location\030\003 \001(\t\022\016\n\006status\030\004 \001" +
      "(\t\022\021\n\texactTemp\030\005 \001(\005\"(\n\023HeaterStatusReq" +
      "uest\022\021\n\theater_id\030\001 \001(\005\"2\n\nexact_temp\022\021\n" +
      "\theater_id\030\001 \001(\005\022\021\n\texactTemp\030\002 \001(\005\"(\n\023H" +
      "eaterUpdateRequest\022\021\n\tdevice_id\030\001 \001(\005\"=\n" +
      "\024HeaterStatusResponse\022%\n\006heater\030\001 \001(\0132\025." +
      "HeatingDevice.Heater\"=\n\024HeaterDetailResp" +
      "onse\022%\n\006heater\030\001 \001(\0132\025.HeatingDevice.Hea" +
      "ter2\240\004\n\rHeaterService\022W\n\nshowStatus\022\".He" +
      "atingDevice.HeaterStatusRequest\032#.Heatin" +
      "gDevice.HeaterStatusResponse\"\000\022]\n\020setTem" +
      "patureHigh\022\".HeatingDevice.HeaterUpdateR" +
      "equest\032#.HeatingDevice.HeaterDetailRespo" +
      "nse\"\000\022\\\n\017setTempaturelow\022\".HeatingDevice" +
      ".HeaterUpdateRequest\032#.HeatingDevice.Hea" +
      "terDetailResponse\"\000\022P\n\014setExactTemp\022\031.He" +
      "atingDevice.exact_temp\032#.HeatingDevice.H" +
      "eaterDetailResponse\"\000\022S\n\006setOff\022\".Heatin" +
      "gDevice.HeaterUpdateRequest\032#.HeatingDev" +
      "ice.HeaterDetailResponse\"\000\022R\n\005setOn\022\".He" +
      "atingDevice.HeaterUpdateRequest\032#.Heatin" +
      "gDevice.HeaterDetailResponse\"\000B$\n\025Heatin" +
      "gDevice.proto.hB\tClassNameP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_HeatingDevice_Heater_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_HeatingDevice_Heater_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_HeatingDevice_Heater_descriptor,
        new java.lang.String[] { "HeaterId", "Device", "DeviceLocation", "Status", "ExactTemp", });
    internal_static_HeatingDevice_HeaterStatusRequest_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_HeatingDevice_HeaterStatusRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_HeatingDevice_HeaterStatusRequest_descriptor,
        new java.lang.String[] { "HeaterId", });
    internal_static_HeatingDevice_exact_temp_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_HeatingDevice_exact_temp_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_HeatingDevice_exact_temp_descriptor,
        new java.lang.String[] { "HeaterId", "ExactTemp", });
    internal_static_HeatingDevice_HeaterUpdateRequest_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_HeatingDevice_HeaterUpdateRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_HeatingDevice_HeaterUpdateRequest_descriptor,
        new java.lang.String[] { "DeviceId", });
    internal_static_HeatingDevice_HeaterStatusResponse_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_HeatingDevice_HeaterStatusResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_HeatingDevice_HeaterStatusResponse_descriptor,
        new java.lang.String[] { "Heater", });
    internal_static_HeatingDevice_HeaterDetailResponse_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_HeatingDevice_HeaterDetailResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_HeatingDevice_HeaterDetailResponse_descriptor,
        new java.lang.String[] { "Heater", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
