// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: HeatingDevice.proto

package HeatingDevice.proto.h;

public interface exact_tempOrBuilder extends
    // @@protoc_insertion_point(interface_extends:HeatingDevice.exact_temp)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 heater_id = 1;</code>
   */
  int getHeaterId();

  /**
   * <code>int32 exactTemp = 2;</code>
   */
  int getExactTemp();
}
