// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: HeatingDevice.proto

package HeatingDevice.proto.h;

/**
 * Protobuf type {@code HeatingDevice.HeaterStatusResponse}
 */
public  final class HeaterStatusResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:HeatingDevice.HeaterStatusResponse)
    HeaterStatusResponseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use HeaterStatusResponse.newBuilder() to construct.
  private HeaterStatusResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private HeaterStatusResponse() {
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private HeaterStatusResponse(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            HeatingDevice.proto.h.Heater.Builder subBuilder = null;
            if (heater_ != null) {
              subBuilder = heater_.toBuilder();
            }
            heater_ = input.readMessage(HeatingDevice.proto.h.Heater.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(heater_);
              heater_ = subBuilder.buildPartial();
            }

            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return HeatingDevice.proto.h.ClassName.internal_static_HeatingDevice_HeaterStatusResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return HeatingDevice.proto.h.ClassName.internal_static_HeatingDevice_HeaterStatusResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            HeatingDevice.proto.h.HeaterStatusResponse.class, HeatingDevice.proto.h.HeaterStatusResponse.Builder.class);
  }

  public static final int HEATER_FIELD_NUMBER = 1;
  private HeatingDevice.proto.h.Heater heater_;
  /**
   * <code>.HeatingDevice.Heater heater = 1;</code>
   */
  public boolean hasHeater() {
    return heater_ != null;
  }
  /**
   * <code>.HeatingDevice.Heater heater = 1;</code>
   */
  public HeatingDevice.proto.h.Heater getHeater() {
    return heater_ == null ? HeatingDevice.proto.h.Heater.getDefaultInstance() : heater_;
  }
  /**
   * <code>.HeatingDevice.Heater heater = 1;</code>
   */
  public HeatingDevice.proto.h.HeaterOrBuilder getHeaterOrBuilder() {
    return getHeater();
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (heater_ != null) {
      output.writeMessage(1, getHeater());
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (heater_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getHeater());
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof HeatingDevice.proto.h.HeaterStatusResponse)) {
      return super.equals(obj);
    }
    HeatingDevice.proto.h.HeaterStatusResponse other = (HeatingDevice.proto.h.HeaterStatusResponse) obj;

    boolean result = true;
    result = result && (hasHeater() == other.hasHeater());
    if (hasHeater()) {
      result = result && getHeater()
          .equals(other.getHeater());
    }
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasHeater()) {
      hash = (37 * hash) + HEATER_FIELD_NUMBER;
      hash = (53 * hash) + getHeater().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static HeatingDevice.proto.h.HeaterStatusResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static HeatingDevice.proto.h.HeaterStatusResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static HeatingDevice.proto.h.HeaterStatusResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static HeatingDevice.proto.h.HeaterStatusResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static HeatingDevice.proto.h.HeaterStatusResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static HeatingDevice.proto.h.HeaterStatusResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static HeatingDevice.proto.h.HeaterStatusResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static HeatingDevice.proto.h.HeaterStatusResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static HeatingDevice.proto.h.HeaterStatusResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static HeatingDevice.proto.h.HeaterStatusResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static HeatingDevice.proto.h.HeaterStatusResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static HeatingDevice.proto.h.HeaterStatusResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(HeatingDevice.proto.h.HeaterStatusResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code HeatingDevice.HeaterStatusResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:HeatingDevice.HeaterStatusResponse)
      HeatingDevice.proto.h.HeaterStatusResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return HeatingDevice.proto.h.ClassName.internal_static_HeatingDevice_HeaterStatusResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return HeatingDevice.proto.h.ClassName.internal_static_HeatingDevice_HeaterStatusResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              HeatingDevice.proto.h.HeaterStatusResponse.class, HeatingDevice.proto.h.HeaterStatusResponse.Builder.class);
    }

    // Construct using HeatingDevice.proto.h.HeaterStatusResponse.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      if (heaterBuilder_ == null) {
        heater_ = null;
      } else {
        heater_ = null;
        heaterBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return HeatingDevice.proto.h.ClassName.internal_static_HeatingDevice_HeaterStatusResponse_descriptor;
    }

    @java.lang.Override
    public HeatingDevice.proto.h.HeaterStatusResponse getDefaultInstanceForType() {
      return HeatingDevice.proto.h.HeaterStatusResponse.getDefaultInstance();
    }

    @java.lang.Override
    public HeatingDevice.proto.h.HeaterStatusResponse build() {
      HeatingDevice.proto.h.HeaterStatusResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public HeatingDevice.proto.h.HeaterStatusResponse buildPartial() {
      HeatingDevice.proto.h.HeaterStatusResponse result = new HeatingDevice.proto.h.HeaterStatusResponse(this);
      if (heaterBuilder_ == null) {
        result.heater_ = heater_;
      } else {
        result.heater_ = heaterBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof HeatingDevice.proto.h.HeaterStatusResponse) {
        return mergeFrom((HeatingDevice.proto.h.HeaterStatusResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(HeatingDevice.proto.h.HeaterStatusResponse other) {
      if (other == HeatingDevice.proto.h.HeaterStatusResponse.getDefaultInstance()) return this;
      if (other.hasHeater()) {
        mergeHeater(other.getHeater());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      HeatingDevice.proto.h.HeaterStatusResponse parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (HeatingDevice.proto.h.HeaterStatusResponse) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private HeatingDevice.proto.h.Heater heater_ = null;
    private com.google.protobuf.SingleFieldBuilderV3<
        HeatingDevice.proto.h.Heater, HeatingDevice.proto.h.Heater.Builder, HeatingDevice.proto.h.HeaterOrBuilder> heaterBuilder_;
    /**
     * <code>.HeatingDevice.Heater heater = 1;</code>
     */
    public boolean hasHeater() {
      return heaterBuilder_ != null || heater_ != null;
    }
    /**
     * <code>.HeatingDevice.Heater heater = 1;</code>
     */
    public HeatingDevice.proto.h.Heater getHeater() {
      if (heaterBuilder_ == null) {
        return heater_ == null ? HeatingDevice.proto.h.Heater.getDefaultInstance() : heater_;
      } else {
        return heaterBuilder_.getMessage();
      }
    }
    /**
     * <code>.HeatingDevice.Heater heater = 1;</code>
     */
    public Builder setHeater(HeatingDevice.proto.h.Heater value) {
      if (heaterBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        heater_ = value;
        onChanged();
      } else {
        heaterBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.HeatingDevice.Heater heater = 1;</code>
     */
    public Builder setHeater(
        HeatingDevice.proto.h.Heater.Builder builderForValue) {
      if (heaterBuilder_ == null) {
        heater_ = builderForValue.build();
        onChanged();
      } else {
        heaterBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.HeatingDevice.Heater heater = 1;</code>
     */
    public Builder mergeHeater(HeatingDevice.proto.h.Heater value) {
      if (heaterBuilder_ == null) {
        if (heater_ != null) {
          heater_ =
            HeatingDevice.proto.h.Heater.newBuilder(heater_).mergeFrom(value).buildPartial();
        } else {
          heater_ = value;
        }
        onChanged();
      } else {
        heaterBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.HeatingDevice.Heater heater = 1;</code>
     */
    public Builder clearHeater() {
      if (heaterBuilder_ == null) {
        heater_ = null;
        onChanged();
      } else {
        heater_ = null;
        heaterBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.HeatingDevice.Heater heater = 1;</code>
     */
    public HeatingDevice.proto.h.Heater.Builder getHeaterBuilder() {
      
      onChanged();
      return getHeaterFieldBuilder().getBuilder();
    }
    /**
     * <code>.HeatingDevice.Heater heater = 1;</code>
     */
    public HeatingDevice.proto.h.HeaterOrBuilder getHeaterOrBuilder() {
      if (heaterBuilder_ != null) {
        return heaterBuilder_.getMessageOrBuilder();
      } else {
        return heater_ == null ?
            HeatingDevice.proto.h.Heater.getDefaultInstance() : heater_;
      }
    }
    /**
     * <code>.HeatingDevice.Heater heater = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        HeatingDevice.proto.h.Heater, HeatingDevice.proto.h.Heater.Builder, HeatingDevice.proto.h.HeaterOrBuilder> 
        getHeaterFieldBuilder() {
      if (heaterBuilder_ == null) {
        heaterBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            HeatingDevice.proto.h.Heater, HeatingDevice.proto.h.Heater.Builder, HeatingDevice.proto.h.HeaterOrBuilder>(
                getHeater(),
                getParentForChildren(),
                isClean());
        heater_ = null;
      }
      return heaterBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:HeatingDevice.HeaterStatusResponse)
  }

  // @@protoc_insertion_point(class_scope:HeatingDevice.HeaterStatusResponse)
  private static final HeatingDevice.proto.h.HeaterStatusResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new HeatingDevice.proto.h.HeaterStatusResponse();
  }

  public static HeatingDevice.proto.h.HeaterStatusResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<HeaterStatusResponse>
      PARSER = new com.google.protobuf.AbstractParser<HeaterStatusResponse>() {
    @java.lang.Override
    public HeaterStatusResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new HeaterStatusResponse(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<HeaterStatusResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<HeaterStatusResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public HeatingDevice.proto.h.HeaterStatusResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

