// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: HeatingDevice.proto

package HeatingDevice.proto.h;

public interface HeaterUpdateRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:HeatingDevice.HeaterUpdateRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 device_id = 1;</code>
   */
  int getDeviceId();
}
