// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: HeatingDevice.proto

package HeatingDevice.proto.h;

public interface HeaterStatusRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:HeatingDevice.HeaterStatusRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 heater_id = 1;</code>
   */
  int getHeaterId();
}
