// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: HeatingDevice.proto

package HeatingDevice.proto.h;

public interface HeaterOrBuilder extends
    // @@protoc_insertion_point(interface_extends:HeatingDevice.Heater)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 heater_id = 1;</code>
   */
  int getHeaterId();

  /**
   * <code>string device = 2;</code>
   */
  java.lang.String getDevice();
  /**
   * <code>string device = 2;</code>
   */
  com.google.protobuf.ByteString
      getDeviceBytes();

  /**
   * <code>string device_location = 3;</code>
   */
  java.lang.String getDeviceLocation();
  /**
   * <code>string device_location = 3;</code>
   */
  com.google.protobuf.ByteString
      getDeviceLocationBytes();

  /**
   * <code>string status = 4;</code>
   */
  java.lang.String getStatus();
  /**
   * <code>string status = 4;</code>
   */
  com.google.protobuf.ByteString
      getStatusBytes();

  /**
   * <code>int32 exactTemp = 5;</code>
   */
  int getExactTemp();
}
