// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: HeatingDevice.proto

package HeatingDevice.proto.h;

public interface HeaterDetailResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:HeatingDevice.HeaterDetailResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.HeatingDevice.Heater heater = 1;</code>
   */
  boolean hasHeater();
  /**
   * <code>.HeatingDevice.Heater heater = 1;</code>
   */
  HeatingDevice.proto.h.Heater getHeater();
  /**
   * <code>.HeatingDevice.Heater heater = 1;</code>
   */
  HeatingDevice.proto.h.HeaterOrBuilder getHeaterOrBuilder();
}
