// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: CarParkOperations.proto

package CarParkOperations.proto.cp;

public interface CarParkToUpdateRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:CarParkOperations.CarParkToUpdateRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 device_id = 1;</code>
   */
  int getDeviceId();
}
