// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: CarParkOperations.proto

package CarParkOperations.proto.cp;

public interface CarParkOrBuilder extends
    // @@protoc_insertion_point(interface_extends:CarParkOperations.CarPark)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 carPark_id = 1;</code>
   */
  int getCarParkId();

  /**
   * <code>string status = 2;</code>
   */
  java.lang.String getStatus();
  /**
   * <code>string status = 2;</code>
   */
  com.google.protobuf.ByteString
      getStatusBytes();

  /**
   * <code>string location = 3;</code>
   */
  java.lang.String getLocation();
  /**
   * <code>string location = 3;</code>
   */
  com.google.protobuf.ByteString
      getLocationBytes();
}
