// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: CarParkOperations.proto

package CarParkOperations.proto.cp;

public interface carparkRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:CarParkOperations.carparkRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 carPark_id = 1;</code>
   */
  int getCarParkId();
}
