// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: CarParkOperations.proto

package CarParkOperations.proto.cp;

/**
 * Protobuf type {@code CarParkOperations.carParkResponse}
 */
public  final class carParkResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:CarParkOperations.carParkResponse)
    carParkResponseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use carParkResponse.newBuilder() to construct.
  private carParkResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private carParkResponse() {
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private carParkResponse(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            CarParkOperations.proto.cp.CarPark.Builder subBuilder = null;
            if (carPark_ != null) {
              subBuilder = carPark_.toBuilder();
            }
            carPark_ = input.readMessage(CarParkOperations.proto.cp.CarPark.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(carPark_);
              carPark_ = subBuilder.buildPartial();
            }

            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return CarParkOperations.proto.cp.ClassName.internal_static_CarParkOperations_carParkResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return CarParkOperations.proto.cp.ClassName.internal_static_CarParkOperations_carParkResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            CarParkOperations.proto.cp.carParkResponse.class, CarParkOperations.proto.cp.carParkResponse.Builder.class);
  }

  public static final int CARPARK_FIELD_NUMBER = 1;
  private CarParkOperations.proto.cp.CarPark carPark_;
  /**
   * <code>.CarParkOperations.CarPark carPark = 1;</code>
   */
  public boolean hasCarPark() {
    return carPark_ != null;
  }
  /**
   * <code>.CarParkOperations.CarPark carPark = 1;</code>
   */
  public CarParkOperations.proto.cp.CarPark getCarPark() {
    return carPark_ == null ? CarParkOperations.proto.cp.CarPark.getDefaultInstance() : carPark_;
  }
  /**
   * <code>.CarParkOperations.CarPark carPark = 1;</code>
   */
  public CarParkOperations.proto.cp.CarParkOrBuilder getCarParkOrBuilder() {
    return getCarPark();
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (carPark_ != null) {
      output.writeMessage(1, getCarPark());
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (carPark_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getCarPark());
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof CarParkOperations.proto.cp.carParkResponse)) {
      return super.equals(obj);
    }
    CarParkOperations.proto.cp.carParkResponse other = (CarParkOperations.proto.cp.carParkResponse) obj;

    boolean result = true;
    result = result && (hasCarPark() == other.hasCarPark());
    if (hasCarPark()) {
      result = result && getCarPark()
          .equals(other.getCarPark());
    }
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasCarPark()) {
      hash = (37 * hash) + CARPARK_FIELD_NUMBER;
      hash = (53 * hash) + getCarPark().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static CarParkOperations.proto.cp.carParkResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static CarParkOperations.proto.cp.carParkResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static CarParkOperations.proto.cp.carParkResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static CarParkOperations.proto.cp.carParkResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static CarParkOperations.proto.cp.carParkResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static CarParkOperations.proto.cp.carParkResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static CarParkOperations.proto.cp.carParkResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static CarParkOperations.proto.cp.carParkResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static CarParkOperations.proto.cp.carParkResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static CarParkOperations.proto.cp.carParkResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static CarParkOperations.proto.cp.carParkResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static CarParkOperations.proto.cp.carParkResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(CarParkOperations.proto.cp.carParkResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code CarParkOperations.carParkResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:CarParkOperations.carParkResponse)
      CarParkOperations.proto.cp.carParkResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return CarParkOperations.proto.cp.ClassName.internal_static_CarParkOperations_carParkResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return CarParkOperations.proto.cp.ClassName.internal_static_CarParkOperations_carParkResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              CarParkOperations.proto.cp.carParkResponse.class, CarParkOperations.proto.cp.carParkResponse.Builder.class);
    }

    // Construct using CarParkOperations.proto.cp.carParkResponse.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      if (carParkBuilder_ == null) {
        carPark_ = null;
      } else {
        carPark_ = null;
        carParkBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return CarParkOperations.proto.cp.ClassName.internal_static_CarParkOperations_carParkResponse_descriptor;
    }

    @java.lang.Override
    public CarParkOperations.proto.cp.carParkResponse getDefaultInstanceForType() {
      return CarParkOperations.proto.cp.carParkResponse.getDefaultInstance();
    }

    @java.lang.Override
    public CarParkOperations.proto.cp.carParkResponse build() {
      CarParkOperations.proto.cp.carParkResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public CarParkOperations.proto.cp.carParkResponse buildPartial() {
      CarParkOperations.proto.cp.carParkResponse result = new CarParkOperations.proto.cp.carParkResponse(this);
      if (carParkBuilder_ == null) {
        result.carPark_ = carPark_;
      } else {
        result.carPark_ = carParkBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof CarParkOperations.proto.cp.carParkResponse) {
        return mergeFrom((CarParkOperations.proto.cp.carParkResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(CarParkOperations.proto.cp.carParkResponse other) {
      if (other == CarParkOperations.proto.cp.carParkResponse.getDefaultInstance()) return this;
      if (other.hasCarPark()) {
        mergeCarPark(other.getCarPark());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      CarParkOperations.proto.cp.carParkResponse parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (CarParkOperations.proto.cp.carParkResponse) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private CarParkOperations.proto.cp.CarPark carPark_ = null;
    private com.google.protobuf.SingleFieldBuilderV3<
        CarParkOperations.proto.cp.CarPark, CarParkOperations.proto.cp.CarPark.Builder, CarParkOperations.proto.cp.CarParkOrBuilder> carParkBuilder_;
    /**
     * <code>.CarParkOperations.CarPark carPark = 1;</code>
     */
    public boolean hasCarPark() {
      return carParkBuilder_ != null || carPark_ != null;
    }
    /**
     * <code>.CarParkOperations.CarPark carPark = 1;</code>
     */
    public CarParkOperations.proto.cp.CarPark getCarPark() {
      if (carParkBuilder_ == null) {
        return carPark_ == null ? CarParkOperations.proto.cp.CarPark.getDefaultInstance() : carPark_;
      } else {
        return carParkBuilder_.getMessage();
      }
    }
    /**
     * <code>.CarParkOperations.CarPark carPark = 1;</code>
     */
    public Builder setCarPark(CarParkOperations.proto.cp.CarPark value) {
      if (carParkBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        carPark_ = value;
        onChanged();
      } else {
        carParkBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.CarParkOperations.CarPark carPark = 1;</code>
     */
    public Builder setCarPark(
        CarParkOperations.proto.cp.CarPark.Builder builderForValue) {
      if (carParkBuilder_ == null) {
        carPark_ = builderForValue.build();
        onChanged();
      } else {
        carParkBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.CarParkOperations.CarPark carPark = 1;</code>
     */
    public Builder mergeCarPark(CarParkOperations.proto.cp.CarPark value) {
      if (carParkBuilder_ == null) {
        if (carPark_ != null) {
          carPark_ =
            CarParkOperations.proto.cp.CarPark.newBuilder(carPark_).mergeFrom(value).buildPartial();
        } else {
          carPark_ = value;
        }
        onChanged();
      } else {
        carParkBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.CarParkOperations.CarPark carPark = 1;</code>
     */
    public Builder clearCarPark() {
      if (carParkBuilder_ == null) {
        carPark_ = null;
        onChanged();
      } else {
        carPark_ = null;
        carParkBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.CarParkOperations.CarPark carPark = 1;</code>
     */
    public CarParkOperations.proto.cp.CarPark.Builder getCarParkBuilder() {
      
      onChanged();
      return getCarParkFieldBuilder().getBuilder();
    }
    /**
     * <code>.CarParkOperations.CarPark carPark = 1;</code>
     */
    public CarParkOperations.proto.cp.CarParkOrBuilder getCarParkOrBuilder() {
      if (carParkBuilder_ != null) {
        return carParkBuilder_.getMessageOrBuilder();
      } else {
        return carPark_ == null ?
            CarParkOperations.proto.cp.CarPark.getDefaultInstance() : carPark_;
      }
    }
    /**
     * <code>.CarParkOperations.CarPark carPark = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        CarParkOperations.proto.cp.CarPark, CarParkOperations.proto.cp.CarPark.Builder, CarParkOperations.proto.cp.CarParkOrBuilder> 
        getCarParkFieldBuilder() {
      if (carParkBuilder_ == null) {
        carParkBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            CarParkOperations.proto.cp.CarPark, CarParkOperations.proto.cp.CarPark.Builder, CarParkOperations.proto.cp.CarParkOrBuilder>(
                getCarPark(),
                getParentForChildren(),
                isClean());
        carPark_ = null;
      }
      return carParkBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:CarParkOperations.carParkResponse)
  }

  // @@protoc_insertion_point(class_scope:CarParkOperations.carParkResponse)
  private static final CarParkOperations.proto.cp.carParkResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new CarParkOperations.proto.cp.carParkResponse();
  }

  public static CarParkOperations.proto.cp.carParkResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<carParkResponse>
      PARSER = new com.google.protobuf.AbstractParser<carParkResponse>() {
    @java.lang.Override
    public carParkResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new carParkResponse(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<carParkResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<carParkResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public CarParkOperations.proto.cp.carParkResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

