// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: CarParkOperations.proto

package CarParkOperations.proto.cp;

public interface carParkResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:CarParkOperations.carParkResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.CarParkOperations.CarPark carPark = 1;</code>
   */
  boolean hasCarPark();
  /**
   * <code>.CarParkOperations.CarPark carPark = 1;</code>
   */
  CarParkOperations.proto.cp.CarPark getCarPark();
  /**
   * <code>.CarParkOperations.CarPark carPark = 1;</code>
   */
  CarParkOperations.proto.cp.CarParkOrBuilder getCarParkOrBuilder();
}
