// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: CarParkOperations.proto

package CarParkOperations.proto.cp;

public final class ClassName {
  private ClassName() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_CarParkOperations_CarPark_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_CarParkOperations_CarPark_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_CarParkOperations_carparkRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_CarParkOperations_carparkRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_CarParkOperations_CarParkToUpdateRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_CarParkOperations_CarParkToUpdateRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_CarParkOperations_allCarp_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_CarParkOperations_allCarp_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_CarParkOperations_carParkResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_CarParkOperations_carParkResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\027CarParkOperations.proto\022\021CarParkOperat" +
      "ions\"?\n\007CarPark\022\022\n\ncarPark_id\030\001 \001(\005\022\016\n\006s" +
      "tatus\030\002 \001(\t\022\020\n\010location\030\003 \001(\t\"$\n\016carpark" +
      "Request\022\022\n\ncarPark_id\030\001 \001(\005\"+\n\026CarParkTo" +
      "UpdateRequest\022\021\n\tdevice_id\030\001 \001(\005\"\031\n\007allC" +
      "arp\022\016\n\006status\030\001 \001(\t\">\n\017carParkResponse\022+" +
      "\n\007carPark\030\001 \001(\0132\032.CarParkOperations.CarP" +
      "ark2\364\002\n\016carParkService\022U\n\nshowStatus\022!.C" +
      "arParkOperations.carparkRequest\032\".CarPar" +
      "kOperations.carParkResponse\"\000\022Z\n\007setFull" +
      "\022).CarParkOperations.CarParkToUpdateRequ" +
      "est\032\".CarParkOperations.carParkResponse\"" +
      "\000\022\\\n\tsetSpaces\022).CarParkOperations.CarPa" +
      "rkToUpdateRequest\032\".CarParkOperations.ca" +
      "rParkResponse\"\000\022Q\n\013allCarParks\022\032.CarPark" +
      "Operations.allCarp\032\".CarParkOperations.c" +
      "arParkResponse\"\0000\001B)\n\032CarParkOperations." +
      "proto.cpB\tClassNameP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_CarParkOperations_CarPark_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_CarParkOperations_CarPark_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_CarParkOperations_CarPark_descriptor,
        new java.lang.String[] { "CarParkId", "Status", "Location", });
    internal_static_CarParkOperations_carparkRequest_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_CarParkOperations_carparkRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_CarParkOperations_carparkRequest_descriptor,
        new java.lang.String[] { "CarParkId", });
    internal_static_CarParkOperations_CarParkToUpdateRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_CarParkOperations_CarParkToUpdateRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_CarParkOperations_CarParkToUpdateRequest_descriptor,
        new java.lang.String[] { "DeviceId", });
    internal_static_CarParkOperations_allCarp_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_CarParkOperations_allCarp_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_CarParkOperations_allCarp_descriptor,
        new java.lang.String[] { "Status", });
    internal_static_CarParkOperations_carParkResponse_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_CarParkOperations_carParkResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_CarParkOperations_carParkResponse_descriptor,
        new java.lang.String[] { "CarPark", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
